=== SIstory/Ortsrepertorium/year1910/XML_Schema/OrtsRprt-wrkg_1-slv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="polOkraji"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="polOkraji">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="polOkraj"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="polOkraj">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="sodniOkraji"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sodniOkraji">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="sodniOkraj"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sodniOkraj">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="obcine"/>
      </xs:sequence>
      <xs:attribute name="n" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="obcine">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="obcina"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="obcina">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="kraji"/>
      </xs:sequence>
      <xs:attribute name="n" type="xs:integer"/>
      <xs:attribute name="ko" type="xs:string">
        <xs:annotation>
          <xs:documentation>vpiši podatke o katastrski občini</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="koopomba" type="xs:string">
        <xs:annotation>
          <xs:documentation>vpiši podatke o katastrski občini iz opombe</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="kraji">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="kraj"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="kraj">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="geo"/>
        <xs:element minOccurs="0" ref="deli"/>
      </xs:sequence>
      <xs:attribute name="n" type="xs:integer"/>
      <xs:attribute name="ko" type="xs:string">
        <xs:annotation>
          <xs:documentation>vpiši podatke o katastrski občini</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="koopomba" type="xs:string">
        <xs:annotation>
          <xs:documentation>vpiši podatke o katastrski občini iz opombe</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="deli">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="del"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="del">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="geo"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="vrsta"/>
          <xs:element ref="hise"/>
          <xs:element ref="prebivalci"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="vrsta" type="xs:string"/>
  <xs:element name="hise" type="xs:integer"/>
  <xs:element name="prebivalci" type="xs:integer"/>
  <xs:element name="placeName">
    <xs:complexType mixed="true">
      <xs:attribute name="key" type="xs:integer"/>
      <xs:attribute name="lang">
        <xs:simpleType>
          <xs:restriction base="xs:language">
            <xs:enumeration value="slv">
              <xs:annotation>
                <xs:documentation>slovenščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="deu">
              <xs:annotation>
                <xs:documentation>nemščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ita">
              <xs:annotation>
                <xs:documentation>italijanščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="hun">
              <xs:annotation>
                <xs:documentation>madžarščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="hrv">
              <xs:annotation>
                <xs:documentation>hrvaščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="geo" type="xs:string"/>
</xs:schema>

=== SIstory/Ortsrepertorium/year1910/Styria/Styria-1910-slv.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../XML_Schema/OrtsRprt-wrkg_1-slv.xsd">
   <polOkraji>
      <polOkraj>
         <placeName>Brežice</placeName>
         <placeName lang="deu">Rann</placeName>
         <sodniOkraji>
            <sodniOkraj n="1">
               <placeName>Brežice</placeName>
               <placeName lang="deu">Rann</placeName>
               <obcine>
                  <obcina n="1">
                     <placeName>Artiče</placeName>
                     <placeName lang="deu">Artitsch</placeName>
                     <kraji>
                        <kraj n="1">
                           <placeName>Arnova Sela</placeName>
                           <placeName lang="deu">Arnovasela</placeName>
                           <deli>
                              <del>
                                 <placeName lang="slv" key="8987036">Arnova Sela</placeName>
                                 <placeName lang="deu">Arnovasela</placeName>
                                 <geo>45.96059, 15.57106</geo>
                              </del>
                              <del>
                                 <placeName key="10793830">Mrzlak</placeName>
                                 <geo>45.96386, 15.57394</geo>
                              </del>
                              <del>
                                 <placeName key="10793831">Ivanje Selo</placeName>
                                 <geo>45.95873, 15.57647</geo>
                              </del>
                              <del>
                                 <placeName>Roviše</placeName>
                              </del>
                           </deli>
                        </kraj>
                        <kraj n="2">
                           <placeName>Artiče</placeName>
                           <placeName lang="deu">Artitsch</placeName>
                           <deli>
                              <del>
                                 <placeName key="3204766">Artiče</placeName>
                                 <placeName lang="deu">Artitsch</placeName>
                                 <geo>45.95389, 15.58778</geo>
                              </del>
                              <del>
                                 <placeName>Kralovec</placeName>
                              </del>
                           </deli>
                        </kraj>
                        <kraj n="3">
                           <placeName>Dečna Sela</placeName>
                           <placeName lang="deu">Detschnasela</placeName>
                           <deli>
                              <del>
                                 <placeName>Brezje</placeName>
                              </del>
                              <del>
                                 <placeName key="3202127">Dečna Sela</placeName>
                                 <placeName lang="deu">Detschnasela</placeName>
                                 <geo>45.95225, 15.60595</geo>
                              </del>
                           </deli>
                        </kraj>
                        <kraj n="4">
                           <placeName>Dolenja Vas</placeName>
                           <placeName lang="deu">Niederdorf</placeName>
                           <deli>
                              <del>
                                 <placeName key="10793836">Čela</placeName>
                                 <geo>45.96595, 15.5575</geo>
                              </del>
                              <del>
                                 <placeName key="8987180">Dolenja Vas</placeName>
                                 <placeName lang="deu">Niederdorf</placeName>
                                 <geo>45.95249, 15.5495</geo>
                              </del>
                           </deli>
                        </kraj>
                        <kraj n="5">
                           <placeName key="8987603">Glogov Brod</placeName>
                           <geo>45.94555, 15.59545</geo>
                        </kraj>
                        <kraj n="6">
                           <placeName>Spodnja Pohanca</placeName>
                           <placeName lang="deu">Unterpochanza</placeName>
                           <deli>
                              <del>
                                 <placeName key="3190240">Spodnja Pohanca</placeName>
                                 <placeName lang="deu">Unterpochanza</placeName>
                                 <geo>45.94778, 15.5657</geo>
                              </del>
                           </deli>
                        </kraj>
                        <kraj n="7">
                           <placeName key="8987097">Trebež</placeName>
                           <placeName lang="deu">Trebesch</placeName>
                           <geo>45.94092, 15.58179</geo>
                        </kraj>
                        <kraj n="8">
                           <placeName key="8987321">Zgornji Obrež</placeName>
                           <placeName lang="deu">Oberobresch</placeName>
                           <geo>45.93898, 15.56429</geo>
                        </kraj>
                        <kraj n="9">
                           <placeName key="8987167">Zverinjak</placeName>
                           <placeName lang="deu">Thiergarten</placeName>
                           <geo>45.92067, 15.57332</geo>
                        </kraj>
                     </kraji>
                  </obcina>
               </obcine>
            </sodniOkraj>
         </sodniOkraji>
      </polOkraj>
   </polOkraji>
</root>
