=== SIstory/Ortsrepertorium/year1910/XML_Schema/OrtsRprt-wrkg_1-deu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="polBezirke"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="polBezirke">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="polBezirk"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="polBezirk">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="gerichtsBezirke"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="gerichtsBezirke">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="gerichtsBezirk"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="gerichtsBezirk">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="gemeinden"/>
      </xs:sequence>
      <xs:attribute name="n" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="gemeinden">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="gemeinde"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="gemeinde">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="orte"/>
      </xs:sequence>
      <xs:attribute name="n" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="orte">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ort"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ort">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="geo"/>
        <xs:element minOccurs="0" ref="teile"/>
      </xs:sequence>
      <xs:attribute name="n" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="teile">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="teil"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="teil">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="placeName"/>
        <xs:element minOccurs="0" ref="geo"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="vrsta"/>
          <xs:element ref="hise"/>
          <xs:element ref="prebivalci"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="vrsta" type="xs:string"/>
  <xs:element name="hise" type="xs:integer"/>
  <xs:element name="prebivalci" type="xs:integer"/>
  <xs:element name="placeName">
    <xs:complexType mixed="true">
      <xs:attribute name="key" type="xs:integer"/>
      <xs:attribute name="lang">
        <xs:simpleType>
          <xs:restriction base="xs:language">
            <xs:enumeration value="slv">
              <xs:annotation>
                <xs:documentation>slovenščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="deu">
              <xs:annotation>
                <xs:documentation>nemščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ita">
              <xs:annotation>
                <xs:documentation>italijanščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="hun">
              <xs:annotation>
                <xs:documentation>madžarščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="hrv">
              <xs:annotation>
                <xs:documentation>hrvaščina</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="geo" type="xs:string"/>
</xs:schema>

=== SIstory/Ortsrepertorium/year1910/Carinthia/Carinthia-1910-deu.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../XML_Schema/OrtsRprt-wrkg_1-deu.xsd">
    <polBezirke>
        <polBezirk>
            <placeName lang="deu" key="2762315">Völkermarkt</placeName>
            <placeName lang="slv" key="2762315">Velikovec</placeName>
            <gerichtsBezirke>
                <gerichtsBezirk n="1">
                    <placeName lang="deu" key="2781703">Bleiburg</placeName>
                    <placeName lang="slv" key="2781703">Pliberk</placeName>
                    <gemeinden>
                        <gemeinde n="1" ko="">
                            <placeName lang="deu" key="2781703">Bleiburg</placeName>
                            <placeName lang="slv" key="2781703">Pliberk</placeName>
                        </gemeinde>
                        <gemeinde n="2">
                            <placeName lang="deu" key="2779703">Feistritz</placeName>
                            <placeName lang="slv" key="2779703">Bistrica</placeName>
                            <orte>
                                <ort n="1">
                                    <placeName lang="deu" key="3214041">Dolintschitschach</placeName>
                                    <placeName lang="slv" key="3214041">Dolinčiče</placeName>
                                </ort>
                                <ort n="2" ko="2, 3, 4 t., 5, 8, 9">
                                    <placeName lang="deu" key="2779703">Feistritz</placeName>
                                    <placeName lang="slv" key="2779703">Bistrica</placeName>
                                </ort>
                                <ort n="3">
                                    <placeName lang="deu" key="2778343">Gonowetz</placeName>
                                    <placeName lang="slv" key="2778343">Gonovece</placeName>
                                </ort>
                                <ort n="4">
                                    <placeName lang="deu" key="3214042">Hinterlibitsch</placeName>
                                    <placeName lang="slv" key="3214042">Podlibič</placeName>
                                </ort>
                                <ort n="5">
                                    <placeName lang="deu" key="2775879">Hof</placeName>
                                    <placeName lang="slv" key="2775879">Dvor</placeName>
                                </ort>
                                <ort n="6">
                                    <placeName lang="deu" key="2772572">Lettenstätten</placeName>
                                    <placeName lang="slv" key="2772572">Letinje</placeName>
                                </ort>
                                <ort n="7" ko="1, 7, 14">
                                    <placeName lang="deu" key="2769139">Penk</placeName>
                                    <placeName lang="slv" key="2769139">Ponikva</placeName>
                                </ort>
                                <ort n="8">
                                    <placeName lang="deu" key="2768778">Pirkdorf</placeName>
                                    <placeName lang="slv" key="2768778">Brežka Ves</placeName>
                                </ort>
                                <ort n="9">
                                    <placeName lang="deu" key="3214048">Ruttach</placeName>
                                    <placeName lang="slv" key="3214048">Rute</placeName>
                                </ort>
                                <ort n="10" ko="4 t., 6, 10, 12">
                                    <placeName lang="deu" key="2766504">Sankt Michael</placeName>
                                    <placeName lang="slv" key="2766504">Šmihel</placeName>
                                </ort>
                                <ort n="11" ko="">
                                    <placeName lang="deu" key="2763419">Traundorf</placeName>
                                    <placeName lang="slv" key="2763419">Strpna Ves</placeName>
                                </ort>
                                <ort n="12">
                                    <placeName lang="deu" key="2763296">Tscherberg</placeName>
                                    <placeName lang="slv" key="2763296">Čergoviče</placeName>
                                </ort>
                                <ort n="13" ko="" koopomba="Unterort 1, Podkraj 1 ko.">
                                    <placeName lang="deu" key="2762738">Unterort</placeName>
                                    <placeName lang="slv" key="2762738">Podkraj</placeName>
                                </ort>
                                <ort n="14"><!-- brez označbe, pod naseljema Penk in Dolinčiče -->
                                    <placeName lang="deu">Winkel</placeName>
                                    <placeName lang="slv">Kot</placeName>
                                </ort>
                            </orte>
                        </gemeinde>
                        <gemeinde n="3">
                            <placeName lang="deu" key="3189025">Fettengupf</placeName>
                            <placeName lang="slv" key="3189025">Tolski Vrh</placeName>
                            <orte>
                                <ort n="1">
                                    <placeName lang="deu" key="3201940">Dobriach</placeName>
                                    <placeName lang="slv" key="3201940">Dobrije</placeName>
                                    <teile>
                                        <teil>
                                            <placeName lang="deu" key="3201940">Dobriach</placeName>
                                            <placeName lang="slv" key="3201940">Dobrije</placeName>
                                            <vrsta>selo</vrsta>
                                            <hise>4</hise>
                                            <prebivalci>34</prebivalci>
                                            <vrsta>raztresene hiše</vrsta>
                                            <hise>10</hise>
                                            <prebivalci>39</prebivalci>
                                        </teil>
                                    </teile>
                                </ort>
                                <ort n="2" ko="2, 7, 8">
                                    <placeName lang="slv" key="8987423">Dobrova</placeName>
                                    <teile>
                                        <teil>
                                            <placeName lang="slv" key="8987423">Dobrova</placeName>
                                            <vrsta>selo</vrsta>
                                            <hise>8</hise>
                                            <prebivalci>54</prebivalci>
                                            <vrsta>raztresene hiše</vrsta>
                                            <hise>11</hise>
                                            <prebivalci>50</prebivalci>
                                        </teil>
                                    </teile>
                                </ort>
                                <ort n="3" ko="">
                                    <placeName lang="deu" key="3189025">Fettengupf</placeName>
                                    <placeName lang="slv" key="3189025">Tolsti Vrh</placeName>
                                </ort>
                                <ort n="4" ko="">
                                    <placeName lang="deu">Gamsenegg</placeName>
                                    <placeName lang="slv">Javornik</placeName>
                                </ort>
                                <ort n="5" ko="">
                                    <placeName lang="deu" key="3186620">Schöllenberg</placeName>
                                    <placeName lang="slv" key="3186620">Šelenberg</placeName>
                                    <teile>
                                        <teil>
                                            <placeName lang="deu" key="3186620">Schöllenberg</placeName>
                                            <placeName lang="slv" key="3186620">Šelenberg</placeName>
                                            <vrsta>selo</vrsta>
                                            <hise>3</hise>
                                            <prebivalci>29</prebivalci>
                                            <vrsta>raztresene hiše</vrsta>
                                            <hise>26</hise>
                                            <prebivalci>176</prebivalci>
                                        </teil>
                                    </teile>
                                </ort>
                                <ort n="6" ko="1, 6">
                                    <placeName lang="deu" key="8986924">Selloutz</placeName>
                                    <placeName lang="slv" key="8986924">Selovec</placeName>
                                </ort>
                                <ort n="7">
                                    <placeName lang="deu">Ueberfuhr</placeName>
                                    <placeName lang="slv">Na Brodu</placeName>
                                </ort>
                                <ort n="8">
                                    <placeName lang="deu" key="8987434">Unterklanz</placeName>
                                    <placeName lang="slv" key="8987434">Pod Klancem</placeName>
                                </ort>
                            </orte>
                        </gemeinde>
                        <gemeinde n="4" ko=""><!-- Ravne na Koroškem -->
                            <placeName lang="deu" key="3191839">Gutenstein</placeName>
                            <placeName lang="slv" key="3191839">Guštanj</placeName>
